#!/bin/bash
# prepare workspace
./reclean
./reformat
# rebuild, and deploy
echo "Rebuild, Reinstall and Redeploy..."
python3 -m build && python3 -m pip install --force-reinstall dist/*.whl && \
python3 -m the_cradle.deployer

