#!/bin/bash
# prepare workspace
./reclean
./reformat
# rebuild, and deploy
echo "Rebuild, Reinstall and Redeploy..."
python3 -m pdm build && python3 -m pip install --force-reinstall dist/*.whl && \
python3 -m the_cradle.deployer

# If failure, stop there
retval=$?
if [ $retval -ne 0 ]; then
    echo ""
    echo "Failed to deploy :("
fi

pnrlog="build/top.tim"
if [ -f "$pnrlog" ]; then
    read -p "See nextpnr logs ? (type 'N' to skip) " confirm
    if [ "$confirm" != "N" ]; then
        more build/top.tim
    fi
fi

exit $retval